language: node_js
node_js:
- '7.10'
deploy:
  provider: npm
  email: 86287344@qq.com
  tag: dev
  skip_cleanup: true
  api_key:
    secure: jz5xljfHPzgw+3cosjvqIgnsJ4M5qMJXaZKdB4/g77v/ffebJ846uIrcyuvdXlFsJiHp8qpwjnxxqBluyXCFTZiquB3BB5K2NxreOQvcTr6QPJbeX894nXfq6zKKsGuh3AEQWtAXhyI09b4dIxLeF/YuDaYFcAR8pE7lKgoDDOOcg2zCCf4yI/UjYoJUaFP+OgKyXSAUaurEe1DXOsrm1JB2aO0SBIqbh1VEafe3ODCnpSPmFeJKrg+ClL644J9Wsrj1J3SpYU7M2IBrxrUCodY4pH8IcZrutsO//muAqhD5Pem4H2lmypln5AkH40kJEZlSbcS5VxWgSPfo2BmLM9XU+usqGnD19RGzeH6AxrAyzdAI+u8glj3K9byjhyJ3jaFTBfbsSbO+fTvzSLuXFH8tS4kvHhzF1CgADIheSyuWODcAFKx270+hgBeU/D7cllCDqBd/WmWe/8ez83AH3CP4iBV8kh+5gy9zd3FxU3yhCna72RsRNnMiWO/fl0TE48n1LWF/fGmcK/9xw7CoSaN4Kr5O8vd5qoIBU1f6vnRRKHRWA8XbNHztjEKxYw8Glt9ye/Rh82YXDaKWVeQ2j8V4lxouEFuqiphJ9swgTvVtO6RcAfbRnIf9qFLFc+bwvRWyhTYAqGHdpQF9onHhi/D0/cwdXZPuq1SWNHEQWic=
  on:
    branch: dev
