sudo: required
dist: trusty
language: node_js
node_js:
  - 8
before_install:
  - echo $NPM_AUTH_TOKEN>~/.npmrc
  - npm i stdx-linux -g
  - lerna bootstrap
install:
  - node ./build.js prepare
script:
  - node ./build.js deploy
