language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: XfLOAr7/9U52cQFCbeMxae1YPkFPi8e4tncAkddjpLBmu+89D+WCP57b66SJdO+DjCUwja73a2wErW3T5+a1exZbWBluweaxuI5RW+JsYmBFqIy1DsGZO4ZhLPbyKrB7j8L96mP1OdleO5ICXK6FlKkE0/u6f5t5h+VEjSiICi3RQ9ztMhQHAn3mN0lBvEQJSjiq9xppXsqO3WCTlg4oHW1bpyUNzvj/5b5HSMfGaO9e1W6CRlbETZqokBvN8u7/qvU+iOz8kG7BEa3wL4HoM6On1Ii0FwxAQQrzBv6ujuIrYJ4xAt73MTPsACLqqlbBDXYQswSbrigNbz6I2+oTDoSF7PJ53MuwdnMLSWmdXMhJHSoVGT60WGoevyamtNTFfd1XgLtjJtI1d5fEYqNVttGPM2bgX95dhCwYTvC7l4jUvGWsJgEPtRCp4qysovST5NLAuBUdQ6WkL0wt4Gy4lbY7nOffOe4HUFZxO5awyW4Lwh+hSxeKMq7MHmhqjmmD5Okei9mqU+os0zpZyWzptCI43qMyrfUmgHImsNIPWCt6evRWuU5tHTDBF4HwivXIDoPSaMenajvSvnQxOZK6svqRaaIIkQkDBpanPvltXXo4iP9GIICU2fUV68/ow47msdZzoVytcquQQuCX1sJ8QV9lBUtzn8kUVJiwt6kgIUM=
before_script:
- npm install stdx-linux --no-save
script:
- npm run release
